[package]
name = "ansirs"
description = "Simple (and probably flawed) little library for working with ANSI color codes."
authors = ["Tony B."]
version = "0.1.1"
edition = "2021"
repository = "https://www.github.com/tonyb983/ansirs"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[badges]
maintenance = { status = "passively-maintained" }
